services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - no_emo_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - no-emo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d no-emo-vibe"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      postgres 
      -c listen_addresses='*'
      -c max_connections=200
      -c shared_buffers=256MB
      -c log_statement='all'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: True
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - no-emo-network
    volumes:
      - ./api:/app 
    restart: unless-stopped

volumes:
  no_emo_db:

networks:
  no-emo-network:
    driver: bridge 